DROP TABLE IF EXISTS SUPPLY;

CREATE TABLE SUPPLY (
  id INTEGER PRIMARY KEY,
  name text NOT NULL,
  num INT NOT NULL
) WITHOUT ROWID;

DROP TABLE IF EXISTS SUPPLIER_SUPPLY;

CREATE TABLE SUPPLIER_SUPPLY (provider_id INTEGER, supply_id INTEGER);
