DROP TABLE IF EXISTS PROVIDERTYPE;

CREATE TABLE
  PROVIDERTYPE (
    id INTEGER PRIMARY KEY
  , name text NOT NULL
  , slug text NULL
  , num INT NOT NULL
  ) WITHOUT ROWID;

DROP TABLE IF EXISTS SUPPLIER_PROVIDERTYPE;

CREATE TABLE
  SUPPLIER_PROVIDERTYPE (provider_id INTEGER, providertype_id INTEGER);
