DROP TABLE IF EXISTS SPECIALITY;

CREATE TABLE SPECIALITY (
  id INTEGER PRIMARY KEY,
  name text NOT NULL,
  num INT NOT NULL
) WITHOUT ROWID;

DROP TABLE IF EXISTS SUPPLIER_SPECIALITY;

CREATE TABLE SUPPLIER_SPECIALITY (provider_id INTEGER, speciality_id INTEGER);
